import{a as w,S as v,i as P}from"./assets/vendor-BfjKTZs6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();let l=1;const S=40;function b(){l=1}function q(){l+=1}async function $(o){const t="49078062-013dc20f7945f56078ec7160a",s=`https://pixabay.com/api/?${new URLSearchParams({key:t,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:S})}`;try{const{data:e,status:r}=await w.get(s);return e}catch(e){throw new Error(`An error occurred: ${e.message}`)}}const f=document.querySelector(".gallery"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function O(){f.innerHTML=""}function x(o){const{hits:t}=o;if(!t.length)return;const a=t.map(s=>{const{largeImageURL:e,webformatURL:r,tags:n,likes:y,views:g,comments:p,downloads:L}=s;return`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${r}" alt="${n}" />
            <div class="info">
              <p>Likes: ${y}</p>
              <p>Views: ${g}</p>
              <p>Comments: ${p}</p>
              <p>Downloads: ${L}</p>
            </div>
          </a>
        </li>`}).join("");f.insertAdjacentHTML("beforeend",a),E.refresh()}document.querySelector(".gallery");const i=document.querySelector(".load-more"),H=document.querySelector(".form"),d=document.querySelector(".search-input"),m=document.querySelector(".loader");let u="";i.classList.add("hide");H.addEventListener("submit",async o=>{o.preventDefault();const t=d.value.trim();if(!t){c("Sorry, there are no images matching your search query. Please try again!");return}u=t,O(),b(),i.classList.add("hide"),await h(u),d.value=""});i.addEventListener("click",async()=>{q(),await h(u)});async function h(o){try{m.classList.remove("hide");const t=await $(o);if(t.hits.length===0&&t.totalHits===0){c("Sorry, there are no images matching your search query. Please try again!");return}x(t),t.hits.length<40||t.hits.length+(l-1)*40>=t.totalHits?(i.classList.add("hide"),c("We're sorry, but you've reached the end of search results.")):i.classList.remove("hide");const{height:a}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch(t){c(t.message)}finally{m.classList.add("hide")}}function c(o){P.error({message:o})}
//# sourceMappingURL=index.js.map
