import{a as w,S as v,i as P}from"./assets/vendor-BfjKTZs6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="49078062-013dc20f7945f56078ec7160a",b=15;function q(){return 1}function $(o){return o+1}async function E(o,t){const s=`https://pixabay.com/api/?${new URLSearchParams({key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:b})}`;try{const{data:e}=await w.get(s);return e}catch(e){throw new Error(`An error occurred: ${e.message}`)}}const f=document.querySelector(".gallery"),O=new v(".gallery a",{captionsData:"alt",captionDelay:250});function x(){f.innerHTML=""}function H(o){const{hits:t}=o;if(!t.length)return;const a=t.map(s=>{const{largeImageURL:e,webformatURL:r,tags:n,likes:y,views:g,comments:p,downloads:L}=s;return`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${r}" alt="${n}" />
            <div class="info">
              <p>Likes: ${y}</p>
              <p>Views: ${g}</p>
              <p>Comments: ${p}</p>
              <p>Downloads: ${L}</p>
            </div>
          </a>
        </li>`}).join("");f.insertAdjacentHTML("beforeend",a),O.refresh()}document.querySelector(".gallery");const i=document.querySelector(".load-more"),I=document.querySelector(".form"),d=document.querySelector(".search-input"),m=document.querySelector(".loader");let u="",c=1;i.classList.add("hide");I.addEventListener("submit",async o=>{o.preventDefault();const t=d.value.trim();if(!t){l("Sorry, there are no images matching your search query. Please try again!");return}u=t,x(),c=q(),i.classList.add("hide"),await h(u),d.value=""});i.addEventListener("click",async()=>{c=$(c),await h(u)});async function h(o){try{m.classList.remove("hide");const t=await E(o,c);if(t.hits.length===0&&t.totalHits===0){l("Sorry, there are no images matching your search query. Please try again!");return}H(t),t.hits.length<15||c*15>=t.totalHits?(i.classList.add("hide"),l("We're sorry, but you've reached the end of search results.")):i.classList.remove("hide");const{height:a}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch(t){l(t.message)}finally{m.classList.add("hide")}}function l(o){P.error({message:o})}
//# sourceMappingURL=index.js.map
